In [2]:
#mount drive
%cd ..
from google.colab import drive
drive.mount('/content/gdrive')

# this creates a symbolic link so that now the path /content/gdrive/My\ Drive/ is equal to /mydrive
!ln -s /content/gdrive/My\ Drive/ /mydrive

# list the contents of /mydrive
!ls /mydrive

#Navigate to /mydrive/yolov4
%cd /mydrive

/
Mounted at /content/gdrive
 Artificial_Intelligencce.docx
'Colab Notebooks'
 computervision
 Deneyap
'Deneyap Çevrimiçi  Yazılım Teknolojileri Ortaokul_14.09.2023.pdf'
 Dilek
'My Drive'
 Ortaokul_Sunumlar_Afişler-20231003T125503Z-001
 Program.gsheet
 spam.csv
'Yapılacaklar Listesi.gsheet'
/content/gdrive/My Drive


In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB

In [3]:
spam_dataset = pd.read_csv("spam.csv")

In [4]:
spam_dataset.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [6]:
spam_dataset['spam'] = spam_dataset['Category'].apply(lambda x: 1 if x == 'spam' else 0)

In [7]:
spam_dataset

Category                                            Message  spam
0         ham  Go until jurong point, crazy.. Available only ...     0
1         ham                      Ok lar... Joking wif u oni...     0
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3         ham  U dun say so early hor... U c already then say...     0
4         ham  Nah I don't think he goes to usf, he lives aro...     0
...       ...                                                ...   ...
5567     spam  This is the 2nd time we have tried 2 contact u...     1
5568      ham               Will ü b going to esplanade fr home?     0
5569      ham  Pity, * was in mood for that. So...any other s...     0
5570      ham  The guy did some bitching but I acted like i'd...     0
5571      ham                         Rofl. Its true to its name     0

[5572 rows x 3 columns]

In [9]:
x_train, x_val, y_train, y_val = train_test_split(spam_dataset.Message, spam_dataset.spam, test_size=0.2, random_state=0)

In [11]:
# x_train
x_train.describe()

count                       4457
unique                      4198
top       Sorry, I'll call later
freq                          26
Name: Message, dtype: object

In [12]:
vectorizer = CountVectorizer()
x_train_count = vectorizer.fit_transform(x_train.values)

In [14]:
x_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [15]:
model = MultinomialNB()
model.fit(x_train_count, y_train)

MultinomialNB()

In [18]:
# test ham(email)
email_ham = [" hey wanna meet u for the game?"]
email_ham_count = vectorizer.transform(email_ham)
email_ham_count.toarray()
# 0 spam olmadığı anlamına gelir
model.predict(email_ham_count)


array([0])

In [ ]:
# test spam

In [19]:
email_spam = [" reward mony click"]
email_spam_count = vectorizer.transform(email_spam)
email_spam_count.toarray()
# 0 spam olmadığı anlamına gelir
model.predict(email_spam_count)

array([1])

In [22]:
# test model
x_val_count = vectorizer.transform(x_val)
# x_test_count.toarray()
model.score(x_val_count, y_val)

0.9865470852017937