In [30]:
#mount drive
%cd ..
from google.colab import drive
drive.mount('/content/gdrive')

# this creates a symbolic link so that now the path /content/gdrive/My\ Drive/ is equal to /mydrive
!ln -s /content/gdrive/My\ Drive/ /mydrive

# list the contents of /mydrive
!ls /mydrive

#Navigate to /mydrive/yolov4
%cd /mydrive

/content/gdrive
Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).
ln: failed to create symbolic link '/mydrive/My Drive': File exists
 Artificial_Intelligencce.docx
'Colab Notebooks'
 computervision
 data.csv
 Deneyap
'Deneyap Çevrimiçi  Yazılım Teknolojileri Ortaokul_14.09.2023.pdf'
 Dilek
 labeling_data.csv
'My Drive'
 Ortaokul_Sunumlar_Afişler-20231003T125503Z-001
 Program.gsheet
'Yapılacaklar Listesi.gsheet'
/content/gdrive/My Drive


In [56]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix

In [32]:
data = pd.read_csv("data.csv")

In [ ]:
#--------------------------- Veri etiketleme yöntemi bu şekilde yapılacak --------------------------

In [33]:

def labeling(dataset, labels):

  # tüm texler küçük harf yapılıyor
  for i in range(len(labels)-1):
      labels[i] = labels[i].lower()

  # print(labels.values().lower())
  labels = {word: index  for index, word in enumerate(labels.values())}

  for text in range(len(dataset)-1):
      dataset[text].lower()

      # liste yapılıyor
      text_dataset = dataset[text].split()

      # arayacağımız texti sözlük formatına getiriyoruz
      words_dataset = {word: index for index, word in enumerate(text_dataset)}

      # searched_word_labels -> sözlük -> 1 boyutu az
      # words_dict -> sözlük 2
      common_keys = []
      for key in labels:
          if key in words_dataset:
              common_keys.append(key)

      row = 0
      print(words_dataset)
      print(labels['say'])
      for word in words_dataset:
        row+=1
        for key in common_keys:
          if word == key:
            print(key)
            data.at[row, 'Label'] = word


  print(data.head())
  print("finish")





In [34]:
dataset = data['Message']
labels = {
  0: 'say',
  1: 'ok',
  2: 'salak'}

labeling(dataset, labels)


Streaming output truncated to the last 5000 lines.
{'Ok...': 0, 'I': 1, 'din': 2, 'get': 3, 'ur': 4, 'msg...': 5}
0
{'Tessy..pls': 0, 'do': 1, 'me': 2, 'a': 3, 'favor.': 4, 'Pls': 5, 'convey': 6, 'my': 7, 'birthday': 18, 'wishes': 9, 'to': 10, 'Nimya..pls': 11, 'dnt': 12, 'forget': 13, 'it.': 14, 'Today': 15, 'is': 16, 'her': 17, 'Shijas': 19}
0
{'Pathaya': 0, 'enketa': 1, 'maraikara': 2, "pa'": 3}
0
{'Even': 0, 'if': 1, 'he': 5, 'my': 3, 'friend': 4, 'is': 6, 'a': 7, 'priest': 8, 'call': 9, 'him': 10, 'now': 11}
0
{'U': 0, 'so': 1, 'lousy,': 2, 'run': 3, 'already': 4, 'come': 5, 'back': 6, 'then': 7, 'half': 8, 'dead...': 9, 'Hee...': 10}
0
{"That's": 0, 'y': 1, 'i': 2, 'said': 3, "it's": 4, 'bad': 5, 'dat': 6, 'all': 7, 'e': 8, 'gals': 9, 'know': 10, 'u...': 11, 'Wat': 12, 'u': 13, 'doing': 14, 'now?': 15}
0
{'Or': 0, 'remind': 1, 'me': 2, 'in': 3, 'a': 4, 'few': 5, 'hrs.': 6}
0
{'I': 0, 'had': 1, 'been': 2, 'hoping': 36, 'i': 59, 'would': 5, 'not': 6, 'have': 20, 'to': 61, 'send': 9

In [ ]:
#--------------------------- veri ön işleme  --------------------------

In [35]:

# LabelEncoder'ı oluştur
encoder = LabelEncoder()

# 'Meyve' sütununu encode et
data['Encoded_Label'] = encoder.fit_transform(data['Label'])

# Encode edilmiş DataFrame'i göster
print(data)

                                                Message Label  Encoded_Label
0     Go until jurong point, crazy.. Available only ...   NaN              2
1                         Ok lar... Joking wif u oni...   say              1
2     Free entry in 2 a wkly comp to win FA Cup fina...    ok              0
3     U dun say so early hor... U c already then say...   say              1
4     Nah I don't think he goes to usf, he lives aro...   say              1
...                                                 ...   ...            ...
5567  This is the 2nd time we have tried 2 contact u...   NaN              2
5568               Will ü b going to esplanade fr home?   NaN              2
5569  Pity, * was in mood for that. So...any other s...   NaN              2
5570  The guy did some bitching but I acted like i'd...   NaN              2
5571                         Rofl. Its true to its name   NaN              2

[5572 rows x 3 columns]


In [36]:
# Result data (model kullanıcak)
data.to_csv('labeling_data.csv', index=False)

In [ ]:
# -------------------------------- Şimdi veriyi model için kullanabiliriz ---------------------

In [38]:
dataset = pd.read_csv("labeling_data.csv")

In [40]:
def data_split(dataset):
  x_train, x_val, y_train, y_val = train_test_split(dataset.Message, dataset.Encoded_Label, test_size=0.2, random_state=0)
  return x_train, x_val, y_train, y_val

In [42]:
x_train, x_val, y_train, y_val = data_split(dataset)

In [43]:
x_train.describe()

count                       4457
unique                      4198
top       Sorry, I'll call later
freq                          26
Name: Message, dtype: object

In [44]:
vectorizer = CountVectorizer()
x_train_count = vectorizer.fit_transform(x_train.values)

In [45]:
x_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
# ------------------------------------- Model --------------------------------

In [46]:
model = MultinomialNB()
model.fit(x_train_count, y_train)

MultinomialNB()

In [ ]:
#---------------------------  local test  ------------------------

In [48]:
# kötü söz içermeyen text
text = [" hey wanna meet u for the game?"]
text_count = vectorizer.transform(text)
text_count.toarray()
#  label değeri sonucu verir
model.predict(text_count)

array([2])

In [73]:
# kötü söz içeren text
new_text = ["Ok lar... Joking wif u oni..." ]
new_text_count = vectorizer.transform(new_text)
new_text_count.toarray()
#  label değeri sonucu verir
model.predict(new_text_count)

array([2])

In [ ]:
#---------------------------  model test  ------------------------

In [66]:
# test model
x_val_count = vectorizer.transform(x_val)
# x_test_count.toarray()
model.score(x_val_count, y_val)

0.9964125560538116

In [64]:
# y_pred = model.predict(x_val_count)